version: '3.8'
services:
    postgresdb:
        image: postgres
        container_name: database_codemonday
        restart: always
        environment:
            POSTGRES_DB: codemonday1
            POSTGRES_USER: haoui
            POSTGRES_PASSWORD: 12345678
        volumes:
            - ./postgres:/var/lib/postgresql/data
        ports:
            - '5432:5432'

    server:
        container_name: express_server
        build: .
        depends_on:
            - postgresdb
        environment:
            NODE_ENV: production
            PORT: 4001
        ports:
            - '4001:4001'
        command: npm run start
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules

volumes:
    app-postgresdb:
